### ISSUE TITLE
Fails to install with "This extension is not installable on any currently installed products"

### ISSUE THREAD

**Issue by apawsey** [BateleurIO/sqlops-combine-scripts#3]
Tried to install the extension from Azure Data Studio but the vsix fails.

```
27/09/2018 02:37:06 - Microsoft VSIX Installer
27/09/2018 02:37:06 - -------------------------------------------
27/09/2018 02:37:06 - vsixinstaller.exe version:
27/09/2018 02:37:06 - 15.8.3252
27/09/2018 02:37:06 - -------------------------------------------
27/09/2018 02:37:06 - Command line parameters:
27/09/2018 02:37:06 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,d:\Users\AdamPawsey\Downloads\sqlops-combine-scripts-1.3.0.vsix
27/09/2018 02:37:06 - -------------------------------------------
27/09/2018 02:37:06 - Microsoft VSIX Installer
27/09/2018 02:37:06 - -------------------------------------------
27/09/2018 02:37:09 - Initializing Install...
27/09/2018 02:37:09 - Extension Details...
27/09/2018 02:37:09 - 	Identifier         : sqlops-combine-scripts
27/09/2018 02:37:09 - 	Name               : Combine Scripts
27/09/2018 02:37:09 - 	Author             : BateleurIO
27/09/2018 02:37:09 - 	Version            : 1.3.0
27/09/2018 02:37:09 - 	Description        : Create a single combined script from several files.
27/09/2018 02:37:09 - 	Locale             : en-US
27/09/2018 02:37:09 - 	MoreInfoURL        : 
27/09/2018 02:37:09 - 	InstalledByMSI     : False
27/09/2018 02:37:09 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
27/09/2018 02:37:09 - 
27/09/2018 02:37:09 - 	SignatureState     : Unsigned
27/09/2018 02:37:09 - 	Supported Products : 
27/09/2018 02:37:09 - 		Microsoft.VisualStudio.Code
27/09/2018 02:37:09 - 			Version : 
27/09/2018 02:37:09 - 
27/09/2018 02:37:09 - 	References         : 
27/09/2018 02:37:09 - Signature Details...
27/09/2018 02:37:09 - 	Extension is not signed.
27/09/2018 02:37:09 - 
27/09/2018 02:37:09 - Searching for applicable products...
27/09/2018 02:37:09 - Found installed product - Global Location
27/09/2018 02:37:09 - Found installed product - ssms
27/09/2018 02:37:09 - Found installed product - Visual Studio Enterprise 2017
27/09/2018 02:37:09 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
Azure Data Studio Version information...
```
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
```

**Comment by CobusKruger** [comment]
Hi @apawsey and thanks for reaching out.

Extensions on SQL Ops Studio (and Azure Data Studio) still doesn't have the slick, intuitive interface as on VS Code. To install the VSIX file, you need to open the command palette (Ctrl+Shift+P) and choose _Extensions: Install from VSIX_ and accept the security warning. From there, it should work well.

I'll update the `readme` as well to reflect this.

Just as a side note: Do you know about the VS Code version?
